services:
  app:
    # -> CHANGE THIS LINE to your actual details <-
    image: ghcr.io/gallenhamph/email-reply-agent:main
    container_name: sophos_email_automator
    restart: unless-stopped
    environment:
      - OLLAMA_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./transcripts:/app/transcripts
      - ./outputs:/app/outputs
      - ./attachments:/app/attachments
      - ./seeds:/app/seeds
    depends_on:
      - chromadb
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  chromadb:
    image: chromadb/chroma:latest
    container_name: sophos_chromadb
    restart: unless-stopped
    volumes:
      - ./chroma_data:/chroma/chroma
    ports:
      - "8000:8000"
