version: '3.8'

services:
  sales_engineer_app:
    build: .
    container_name: se_automator_app
    restart: unless-stopped
    environment:
      # --- USER CONFIGURATION ---
      - SE_NAME=Bradley Collis #<------ Change THIS!!!
      - SE_COMPANY=Sophos and Secureworks
      # --------------------------
      - OLLAMA_URL=http://host.docker.internal:11434
    volumes:
      - ./transcripts:/app/transcripts
      - ./outputs:/app/outputs
      - ./attachments:/app/attachments
      - ./seeds:/app/seeds
      - ./glossary.yml:/app/glossary.yml
    depends_on:
      - chromadb
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  chromadb:
    image: chromadb/chroma:latest
    container_name: se_automator_chromadb
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/chroma

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --label-enable --cleanup